### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by victorhugormoura** [routeviews/public-issues#166] opened 2024-09-16 19:11 UTC
### Full Name

Victor Hugo R. Moura

### ASN

269641

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

187.16.219.166 - 187.16.208.39
2001:12f8::219:166 - 2001:12f8::208:39

### Multihop

- [ ] Multihop Peering Request

**Comment by pfsinoz** [comment] 2024-09-27 15:07
Duplicate of https://github.com/routeviews/issues/issues/167

**Closed as completed by pfsinoz** 2024-09-27 15:07 UTC
Labels: triage
